@echo off
echo Starting ML Trading Backend...
cd backend
echo Installing dependencies if missing...
pip install -r requirements.txt
echo Starting FastAPI server...
python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
pause
